services:
  backend:
    image: backend
    build: ./backend/
    container_name: backend-news
    ports:
      - "8000:8000"

  frontend:
    image: frontend
    build: ./frontend/
    container_name: frontend-news
    ports:
    - "5173:5173"

    # Specifies directories/files to watch for changes.
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
   
